// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/lp/music-chart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MusicUsecase is an autogenerated mock type for the MusicUsecase type
type MusicUsecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx, params
func (_m *MusicUsecase) GetAll(ctx context.Context, params models.BasicSelectParams) (*models.GetAllResponse, error) {
	ret := _m.Called(ctx, params)

	var r0 *models.GetAllResponse
	if rf, ok := ret.Get(0).(func(context.Context, models.BasicSelectParams) *models.GetAllResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GetAllResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.BasicSelectParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MusicUsecase) GetByID(ctx context.Context, id uint64) (*models.Music, int, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Music
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *models.Music); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Music)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, uint64) int); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
