// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/lp/music-chart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx, limit, offset
func (_m *Repository) GetAll(ctx context.Context, limit uint64, offset uint64) ([]*models.Music, uint64, error) {
	ret := _m.Called(ctx, limit, offset)

	var r0 []*models.Music
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []*models.Music); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Music)
		}
	}

	var r1 uint64
	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) uint64); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, uint64, uint64) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id uint64) (*models.Music, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Music
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *models.Music); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Music)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
