// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/lp/music-chart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, userID, musicID
func (_m *Repository) Delete(ctx context.Context, userID uint64, musicID uint64) (int64, error) {
	ret := _m.Called(ctx, userID, musicID)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) int64); ok {
		r0 = rf(ctx, userID, musicID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, userID, musicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, f
func (_m *Repository) Insert(ctx context.Context, f models.Favorite) error {
	ret := _m.Called(ctx, f)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Favorite) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
